version: '3'
services:
  keycape:
    image: baaka/keycape:latest
    ports:
      - '8080:8080'
    volumes:
      - ./keycape.yaml:/app/config.yaml
    depends_on: 
      - postgres
  postgres:
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
