name: Deploy Backend
on:
  push:
    branches: [ master ]
    paths: 
      - "backend/**/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BACKEND_HOST }}
        username: ${{ secrets.BACKEND_USERNAME }}
        key: ${{ secrets.BACKEND_SSH_KEY }}
        script: cd ~/workspace/Novel && git pull && cd .. && docker-compose up --detach --build
